In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [129]:
df=pd.read_csv(r'C:\Users\Hi\Desktop\Customer churn prediction\notebooks\Telco_customer.csv')

In [130]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [131]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [132]:
df.drop(['customerID'],axis=1,inplace=True)

In [133]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [134]:
df.columns=df.columns.str.capitalize()

In [135]:
df

,Gender,Seniorcitizen,Partner,Dependents,Tenure,Phoneservice,Multiplelines,Internetservice,Onlinesecurity,Onlinebackup,Deviceprotection,Techsupport,Streamingtv,Streamingmovies,Contract,Paperlessbilling,Paymentmethod,Monthlycharges,Totalcharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [136]:
df.isnull().sum()

Gender              0
Seniorcitizen       0
Partner             0
Dependents          0
Tenure              0
Phoneservice        0
Multiplelines       0
Internetservice     0
Onlinesecurity      0
Onlinebackup        0
Deviceprotection    0
Techsupport         0
Streamingtv         0
Streamingmovies     0
Contract            0
Paperlessbilling    0
Paymentmethod       0
Monthlycharges      0
Totalcharges        0
Churn               0
dtype: int64

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            7043 non-null   object
 1   Seniorcitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   Tenure            7043 non-null   int64
 5   Phoneservice      7043 non-null   object
 6   Multiplelines     7043 non-null   object
 7   Internetservice   7043 non-null   object
 8   Onlinesecurity    7043 non-null   object
 9   Onlinebackup      7043 non-null   object
 10  Deviceprotection  7043 non-null   object
 11  Techsupport       7043 non-null   object
 12  Streamingtv       7043 non-null   object
 13  Streamingmovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  Paperlessbilling  7043 non-null   object
 16  Paymentmethod     7043 non-null   object
 17  Monthlycharges    7043 non-null   float64
 18  Totalcharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [138]:
df['Totalcharges'] = df['Totalcharges'].replace(' ', np.nan)

In [139]:
df['Totalcharges'] = pd.to_numeric(df['Totalcharges'])

In [140]:
df['Totalcharges'].isnull().sum()

np.int64(11)

In [141]:
df['Totalcharges']=df['Totalcharges'].astype(float)

In [142]:
df.isnull().sum()

Gender               0
Seniorcitizen        0
Partner              0
Dependents           0
Tenure               0
Phoneservice         0
Multiplelines        0
Internetservice      0
Onlinesecurity       0
Onlinebackup         0
Deviceprotection     0
Techsupport          0
Streamingtv          0
Streamingmovies      0
Contract             0
Paperlessbilling     0
Paymentmethod        0
Monthlycharges       0
Totalcharges        11
Churn                0
dtype: int64

In [143]:
df[df['Totalcharges'].isnull()][['Tenure', 'Monthlycharges']]

      Tenure  Monthlycharges
488        0           52.55
753        0           20.25
936        0           80.85
1082       0           25.75
1340       0           56.05
3331       0           19.85
3826       0           25.35
4380       0           20.00
5218       0           19.70
6670       0           73.35
6754       0           61.90

In [144]:
df['Totalcharges'] = df['Totalcharges'].fillna(df['Monthlycharges'] * df['Tenure'])

In [145]:
df['Totalcharges'].isnull().sum()

np.int64(0)

In [146]:
df['Churn']=np.where(df['Churn'].str.contains('No'),0,1)

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            7043 non-null   object
 1   Seniorcitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   Tenure            7043 non-null   int64
 5   Phoneservice      7043 non-null   object
 6   Multiplelines     7043 non-null   object
 7   Internetservice   7043 non-null   object
 8   Onlinesecurity    7043 non-null   object
 9   Onlinebackup      7043 non-null   object
 10  Deviceprotection  7043 non-null   object
 11  Techsupport       7043 non-null   object
 12  Streamingtv       7043 non-null   object
 13  Streamingmovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  Paperlessbilling  7043 non-null   object
 16  Paymentmethod     7043 non-null   object
 17  Monthlycharges    7043 non-null   float64
 18  Totalcharges      7043 non-null   float64
 19  Churn             7043 non-null   int64
dtypes: float64(2), int64(3), object(15)
memory usage: 1.1+ MB

In [148]:
X=df.drop('Churn',axis=1)

In [149]:
y=df['Churn']

In [150]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [151]:
y.value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [152]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [153]:
cat_features=X.select_dtypes(include="object").columns
num_features=X.select_dtypes(exclude="object").columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')


preprocessor= ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numeric_transformer,num_features)
    ]
)

In [154]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['Gender', 'Partner', 'Dependents', 'Phoneservice', 'Multiplelines',
       'Internetservice', 'Onlinesecurity', 'Onlinebackup', 'Deviceprotection',
       'Techsupport', 'Streamingtv', 'Streamingmovies', 'Contract',
       'Paperlessbilling', 'Paymentmethod'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Seniorcitizen', 'Tenure', 'Monthlycharges', 'Totalcharges'], dtype='object'))])

In [155]:
X_train=preprocessor.fit_transform(X_train)

In [156]:
X_test=preprocessor.transform(X_test)

In [157]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score,roc_curve

In [158]:
models={
    "Logistic Regression":LogisticRegression(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "knn":KNeighborsClassifier(),
    "Adaboost":AdaBoostClassifier(),
    "SVC":SVC()
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)


    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    model_train_accuracy=accuracy_score(y_train,y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred)
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_recall=recall_score(y_train,y_train_pred)
    model_train_rocauc_score=roc_auc_score(y_train,y_train_pred)

    model_test_accuracy=accuracy_score(y_test,y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred)
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_recall=recall_score(y_test,y_test_pred)
    model_test_rocauc_score=roc_auc_score(y_test,y_test_pred)

    print(list(models.keys())[i])

    print('Model Performance for Training set')
    print("Accuracy:  {:.4f}".format(model_train_accuracy))
    print("F1_score:  {:.4f}".format(model_train_f1))
    print("Precision:  {:.4f}".format(model_train_precision))
    print("Recall:  {:.4f}".format(model_train_recall))
    print("RocAuc_score:  {:.4f}".format(model_train_rocauc_score))

    
    print('Model Performance for Test set')
    print("Accuracy:  {:.4f}".format(model_test_accuracy))
    print("F1_score:  {:.4f}".format(model_test_f1))
    print("Precision:  {:.4f}".format(model_test_precision))
    print("Recall:  {:.4f}".format(model_test_recall))
    print("RocAuc_score:  {:.4f}".format(model_test_rocauc_score))

    print('===================================================================')

Logistic Regression
Model Performance for Training set
Accuracy:  0.8039
F1_score:  0.5939
Precision:  0.6596
Recall:  0.5401
RocAuc_score:  0.7197
Model Performance for Test set
Accuracy:  0.8211
F1_score:  0.6390
Precision:  0.6862
Recall:  0.5979
RocAuc_score:  0.7497
===================================================================
Decision Tree
Model Performance for Training set
Accuracy:  0.9986
F1_score:  0.9973
Precision:  0.9987
Recall:  0.9960
RocAuc_score:  0.9978
Model Performance for Test set
Accuracy:  0.7182
F1_score:  0.4742
Precision:  0.4686
Recall:  0.4799
RocAuc_score:  0.6420
===================================================================
Random Forest
Model Performance for Training set
Accuracy:  0.9986
F1_score:  0.9973
Precision:  0.9967
Recall:  0.9980
RocAuc_score:  0.9984
Model Performance for Test set
Accuracy:  0.7949
F1_score:  0.5491
Precision:  0.6567
Recall:  0.4718
RocAuc_score:  0.6915
===================================================================
knn
Model Performance for Training set
Accuracy:  0.8360
F1_score:  0.6769
Precision:  0.7097
Recall:  0.6471
RocAuc_score:  0.7757
Model Performance for Test set
Accuracy:  0.7729
F1_score:  0.5480
Precision:  0.5791
Recall:  0.5201
RocAuc_score:  0.6920
===================================================================
Adaboost
Model Performance for Training set
Accuracy:  0.8042
F1_score:  0.5827
Precision:  0.6713
Recall:  0.5147
RocAuc_score:  0.7118
Model Performance for Test set
Accuracy:  0.8141
F1_score:  0.6101
Precision:  0.6856
Recall:  0.5496
RocAuc_score:  0.7294
===================================================================
SVC
Model Performance for Training set
Accuracy:  0.8138
F1_score:  0.5875
Precision:  0.7135
Recall:  0.4993
RocAuc_score:  0.7134
Model Performance for Test set
Accuracy:  0.8105
F1_score:  0.5848
Precision:  0.6963
Recall:  0.5040
RocAuc_score:  0.7124
===================================================================

In [159]:
lr_params={'penalty':['l1', 'l2', 'elasticnet', None],
           'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
           'C': [0.01,0.1,1.0,10,100],
           'class_weight':[None,'balanced']
}
adaboost_params={"n_estimators":[50,60,70,80,90],
                 "algorithm":['SAMME','SAMME.R']
}

In [160]:
randomcv_models=[
    ('LR',LogisticRegression(),lr_params),
    ("adaboost",AdaBoostClassifier(),adaboost_params),

]

In [161]:
randomcv_models

[('LR',
  LogisticRegression(),
  {'penalty': ['l1', 'l2', 'elasticnet', None],
   'solver': ['lbfgs',
    'liblinear',
    'newton-cg',
    'newton-cholesky',
    'sag',
    'saga'],
   'C': [0.01, 0.1, 1.0, 10, 100],
   'class_weight': [None, 'balanced']}),
 ('adaboost',
  AdaBoostClassifier(),
  {'n_estimators': [50, 60, 70, 80, 90], 'algorithm': ['SAMME', 'SAMME.R']})]

In [162]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import RandomizedSearchCV

model_param={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,
                              n_iter=100,
                              cv=3,
                              verbose=2,
                              n_jobs=-1)
    random.fit(X_train,y_train)
    model_param[name]=random.best_params_

for model_name in model_param:
    print(f"-----------Best Params for {model_name}--------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 10 candidates, totalling 30 fits
-----------Best Params for LR--------------
{'solver': 'newton-cg', 'penalty': None, 'class_weight': None, 'C': 100}
-----------Best Params for adaboost--------------
{'n_estimators': 70, 'algorithm': 'SAMME'}

In [163]:
classifier=LogisticRegression(solver='newton-cg',class_weight=None,C=0.1)
classifier.fit(X_train,y_train)

LogisticRegression(C=0.1, solver='newton-cg')

In [164]:
y_train_pred=classifier.predict(X_train)
y_test_pred=classifier.predict(X_test)

model_train_accuracy=accuracy_score(y_train,y_train_pred)
model_train_f1=f1_score(y_train,y_train_pred)
model_train_precision=precision_score(y_train,y_train_pred)
model_train_recall=recall_score(y_train,y_train_pred)
model_train_rocauc_score=roc_auc_score(y_train,y_train_pred)

model_test_accuracy=accuracy_score(y_test,y_test_pred)
model_test_f1=f1_score(y_test,y_test_pred)
model_test_precision=precision_score(y_test,y_test_pred)
model_test_recall=recall_score(y_test,y_test_pred)
model_test_rocauc_score=roc_auc_score(y_test,y_test_pred)

print('Model Performance for Training set')
print("Accuracy:  {:.4f}".format(model_train_accuracy))
print("F1_score:  {:.4f}".format(model_train_f1))
print("Precision:  {:.4f}".format(model_train_precision))
print("Recall:  {:.4f}".format(model_train_recall))
print("RocAuc_score:  {:.4f}".format(model_train_rocauc_score))


print('===================================================================')

print('Model Performance for Test set')
print("Accuracy:  {:.4f}".format(model_test_accuracy))
print("F1_score:  {:.4f}".format(model_test_f1))
print("Precision:  {:.4f}".format(model_test_precision))
print("Recall:  {:.4f}".format(model_test_recall))
print("RocAuc_score:  {:.4f}".format(model_test_rocauc_score))

Model Performance for Training set
Accuracy:  0.8012
F1_score:  0.5846
Precision:  0.6567
Recall:  0.5267
RocAuc_score:  0.7136
===================================================================
Model Performance for Test set
Accuracy:  0.8204
F1_score:  0.6328
Precision:  0.6899
Recall:  0.5845
RocAuc_score:  0.7449

In [173]:
import os
import pickle
save_path = r"C:\Users\Hi\Desktop\Customer churn prediction\models"

os.makedirs(save_path, exist_ok=True)

with open(os.path.join(save_path, "preprocessor.pkl"), "wb") as f:
    pickle.dump(preprocessor, f)

with open(os.path.join(save_path, "classifier.pkl"), "wb") as f:
    pickle.dump(classifier, f)